import { tiered5 } from "./bundles-five-tier-cumulative-helper";

export const ORL_MUSIC_A = tiered5({
  room: "Bedroom Orly",
  bundle_code: "ORL-MUSIC-A",
  name: "Music Production Setup",
  description: "Home studio and music production equipment",
  total_value: 6800,
  sweet_spot: true,
  plausibility: "easy",
  essential: {
    total: 1800,
    items: [
      { description: "MIDI keyboard controller 49 key", brand: "Arturia", unit_cost: 280, qty: 1, total: 280, category: "Electronics" },
      { description: "Audio interface 2-in 2-out", brand: "Focusrite", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "Studio monitor speakers", brand: "Yamaha", unit_cost: 380, qty: 2, total: 760, category: "Electronics" },
      { description: "XLR cables 10ft", brand: "Mogami", unit_cost: 28, qty: 4, total: 112, category: "Electronics" },
      { description: "USB MIDI cables", brand: "", unit_cost: 18, qty: 3, total: 54, category: "Electronics" },
    ],
  },
  enhanced: {
    total: 3600,
    items: [
      { description: "MIDI keyboard 49 key", brand: "Arturia", unit_cost: 280, qty: 1, total: 280, category: "Electronics" },
      { description: "Focusrite audio interface", brand: "Focusrite", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "Yamaha studio monitors ×2", brand: "Yamaha", unit_cost: 380, qty: 2, total: 760, category: "Electronics" },
      { description: "XLR cables ×6", brand: "Mogami", unit_cost: 28, qty: 6, total: 168, category: "Electronics" },
      { description: "MIDI pad controller", brand: "Akai", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "Drum machine Roland TR-8S", brand: "Roland", unit_cost: 480, qty: 1, total: 480, category: "Electronics" },
      { description: "Headphones studio Sony MDR", brand: "Sony", unit_cost: 180, qty: 2, total: 360, category: "Electronics" },
      { description: "Microphone condenser USB", brand: "Audio-Technica", unit_cost: 150, qty: 1, total: 150, category: "Electronics" },
    ],
  },
  complete: {
    total: 5400,
    items: [
      { description: "MIDI keyboard 61 key", brand: "Arturia", unit_cost: 380, qty: 1, total: 380, category: "Electronics" },
      { description: "Focusrite Scarlett 4i4 interface", brand: "Focusrite", unit_cost: 280, qty: 1, total: 280, category: "Electronics" },
      { description: "Yamaha HS8 studio monitors ×2", brand: "Yamaha", unit_cost: 450, qty: 2, total: 900, category: "Electronics" },
      { description: "XLR cables ×8", brand: "Mogami", unit_cost: 28, qty: 8, total: 224, category: "Electronics" },
      { description: "Akai MPC pad", brand: "Akai", unit_cost: 280, qty: 1, total: 280, category: "Electronics" },
      { description: "Roland drum machine", brand: "Roland", unit_cost: 480, qty: 1, total: 480, category: "Electronics" },
      { description: "Studio headphones ×3", brand: "Sony", unit_cost: 180, qty: 3, total: 540, category: "Electronics" },
      { description: "Condenser mic Audio-Technica", brand: "Audio-Technica", unit_cost: 150, qty: 2, total: 300, category: "Electronics" },
      { description: "Acoustic foam panels 12-pack", brand: "Acoustimac", unit_cost: 85, qty: 3, total: 255, category: "Electronics" },
      { description: "Monitor stands desktop pair", brand: "IsoAcoustics", unit_cost: 120, qty: 1, total: 120, category: "Electronics" },
      { description: "MIDI thru box", brand: "Kenton", unit_cost: 65, qty: 1, total: 65, category: "Electronics" },
    ],
  },
  full: {
    total: 8200,
    items: [
      { description: "Arturia KeyLab 61 MIDI", brand: "Arturia", unit_cost: 380, qty: 1, total: 380, category: "Electronics" },
      { description: "Focusrite Scarlett 18i20", brand: "Focusrite", unit_cost: 580, qty: 1, total: 580, category: "Electronics" },
      { description: "Adam Audio T7V studio monitors ×2", brand: "Adam Audio", unit_cost: 350, qty: 2, total: 700, category: "Electronics" },
      { description: "XLR cables ×10", brand: "Mogami", unit_cost: 28, qty: 10, total: 280, category: "Electronics" },
      { description: "Akai MPC Live II sampler", brand: "Akai", unit_cost: 980, qty: 1, total: 980, category: "Electronics" },
      { description: "Roland drum machines ×2", brand: "Roland", unit_cost: 480, qty: 2, total: 960, category: "Electronics" },
      { description: "Studio headphones ×4", brand: "Sony", unit_cost: 180, qty: 4, total: 720, category: "Electronics" },
      { description: "Condenser mics ×3", brand: "Audio-Technica", unit_cost: 150, qty: 3, total: 450, category: "Electronics" },
      { description: "Acoustic foam panels ×36", brand: "Acoustimac", unit_cost: 85, qty: 6, total: 510, category: "Electronics" },
      { description: "Monitor stands ×2 pairs", brand: "IsoAcoustics", unit_cost: 120, qty: 2, total: 240, category: "Electronics" },
      { description: "Patch bay 48-point", brand: "Neutrik", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "Synthesizer Korg Minilogue", brand: "Korg", unit_cost: 450, qty: 1, total: 450, category: "Electronics" },
    ],
  },
  ultimate: {
    total: 12000,
    items: [
      { description: "Arturia KeyLab 88 MIDI", brand: "Arturia", unit_cost: 580, qty: 1, total: 580, category: "Electronics" },
      { description: "Universal Audio Apollo interface", brand: "Universal Audio", unit_cost: 1299, qty: 1, total: 1299, category: "Electronics" },
      { description: "Focal Alpha 65 monitors ×2", brand: "Focal", unit_cost: 650, qty: 2, total: 1300, category: "Electronics" },
      { description: "Mogami XLR cables ×12", brand: "Mogami", unit_cost: 28, qty: 12, total: 336, category: "Electronics" },
      { description: "Akai MPC Live ×2", brand: "Akai", unit_cost: 980, qty: 2, total: 1960, category: "Electronics" },
      { description: "Roland machines ×3", brand: "Roland", unit_cost: 480, qty: 3, total: 1440, category: "Electronics" },
      { description: "Studio headphones ×6", brand: "Sony", unit_cost: 180, qty: 6, total: 1080, category: "Electronics" },
      { description: "Condenser mics ×4", brand: "Audio-Technica", unit_cost: 150, qty: 4, total: 600, category: "Electronics" },
      { description: "Acoustic panels full room", brand: "Acoustimac", unit_cost: 85, qty: 12, total: 1020, category: "Electronics" },
      { description: "Korg synthesizers ×2", brand: "Korg", unit_cost: 450, qty: 2, total: 900, category: "Electronics" },
      { description: "Moog Subsequent 25 synth", brand: "Moog", unit_cost: 780, qty: 1, total: 780, category: "Electronics" },
      { description: "Rack mount case 12U", brand: "Gator", unit_cost: 280, qty: 1, total: 280, category: "Electronics" },
    ],
  },
});

export const ORL_STREAM_A = tiered5({
  room: "Bedroom Orly",
  bundle_code: "ORL-STREAM-A",
  name: "Streaming & Content Creation",
  description: "Professional streaming and content creation setup",
  total_value: 5800,
  sweet_spot: true,
  plausibility: "easy",
  essential: {
    total: 1400,
    items: [
      { description: "Elgato Stream Deck MK2", brand: "Elgato", unit_cost: 150, qty: 1, total: 150, category: "Electronics" },
      { description: "Elgato Key Light Air ×2", brand: "Elgato", unit_cost: 130, qty: 2, total: 260, category: "Electronics" },
      { description: "Green screen Elgato collapsible", brand: "Elgato", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "USB webcam 4K Logitech", brand: "Logitech", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "USB microphone Rode NT-USB", brand: "Rode", unit_cost: 170, qty: 1, total: 170, category: "Electronics" },
    ],
  },
  enhanced: {
    total: 2800,
    items: [
      { description: "Elgato Stream Deck MK2", brand: "Elgato", unit_cost: 150, qty: 1, total: 150, category: "Electronics" },
      { description: "Elgato Key Light Air ×2", brand: "Elgato", unit_cost: 130, qty: 2, total: 260, category: "Electronics" },
      { description: "Elgato green screen", brand: "Elgato", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "Logitech 4K webcam", brand: "Logitech", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "Rode NT-USB microphone", brand: "Rode", unit_cost: 170, qty: 1, total: 170, category: "Electronics" },
      { description: "Elgato 4K60 Pro capture card", brand: "Elgato", unit_cost: 200, qty: 1, total: 200, category: "Electronics" },
      { description: "Elgato Stream Deck XL", brand: "Elgato", unit_cost: 250, qty: 1, total: 250, category: "Electronics" },
      { description: "Mic arm professional", brand: "Elgato", unit_cost: 95, qty: 1, total: 95, category: "Electronics" },
      { description: "Ring light 18in", brand: "Elgato", unit_cost: 120, qty: 1, total: 120, category: "Electronics" },
    ],
  },
  complete: {
    total: 4200,
    items: [
      { description: "Elgato Stream Deck MK2 ×2", brand: "Elgato", unit_cost: 150, qty: 2, total: 300, category: "Electronics" },
      { description: "Elgato Key Lights ×4", brand: "Elgato", unit_cost: 130, qty: 4, total: 520, category: "Electronics" },
      { description: "Elgato green screen large", brand: "Elgato", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "Sony ZV-E10 streaming camera", brand: "Sony", unit_cost: 750, qty: 1, total: 750, category: "Electronics" },
      { description: "Rode NT-USB mics ×2", brand: "Rode", unit_cost: 170, qty: 2, total: 340, category: "Electronics" },
      { description: "Elgato 4K60 Pro capture ×2", brand: "Elgato", unit_cost: 200, qty: 2, total: 400, category: "Electronics" },
      { description: "Elgato Stream Deck XL ×2", brand: "Elgato", unit_cost: 250, qty: 2, total: 500, category: "Electronics" },
      { description: "Mic arms ×2", brand: "Elgato", unit_cost: 95, qty: 2, total: 190, category: "Electronics" },
      { description: "LED panels for streaming ×4", brand: "Elgato", unit_cost: 120, qty: 4, total: 480, category: "Electronics" },
      { description: "Monitor arm dual", brand: "Ergotron", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
    ],
  },
  full: {
    total: 5800,
    items: [
      { description: "Elgato Stream Decks ×3", brand: "Elgato", unit_cost: 150, qty: 3, total: 450, category: "Electronics" },
      { description: "Elgato Key Lights ×6", brand: "Elgato", unit_cost: 130, qty: 6, total: 780, category: "Electronics" },
      { description: "Green screens ×2", brand: "Elgato", unit_cost: 180, qty: 2, total: 360, category: "Electronics" },
      { description: "Sony ZV-E10 cameras ×2", brand: "Sony", unit_cost: 750, qty: 2, total: 1500, category: "Electronics" },
      { description: "Rode mics ×3", brand: "Rode", unit_cost: 170, qty: 3, total: 510, category: "Electronics" },
      { description: "Elgato capture cards ×3", brand: "Elgato", unit_cost: 200, qty: 3, total: 600, category: "Electronics" },
      { description: "Stream Deck XLs ×2", brand: "Elgato", unit_cost: 250, qty: 2, total: 500, category: "Electronics" },
      { description: "Mic arms ×3", brand: "Elgato", unit_cost: 95, qty: 3, total: 285, category: "Electronics" },
      { description: "LED panels ×6", brand: "Elgato", unit_cost: 120, qty: 6, total: 720, category: "Electronics" },
      { description: "Monitor arms ×2", brand: "Ergotron", unit_cost: 180, qty: 2, total: 360, category: "Electronics" },
      { description: "Teleprompter tablet mount", brand: "Parrot", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
    ],
  },
  ultimate: {
    total: 9800,
    items: [
      { description: "Elgato Stream Decks ×4", brand: "Elgato", unit_cost: 150, qty: 4, total: 600, category: "Electronics" },
      { description: "Elgato Key Lights ×8", brand: "Elgato", unit_cost: 130, qty: 8, total: 1040, category: "Electronics" },
      { description: "Green screens ×3", brand: "Elgato", unit_cost: 180, qty: 3, total: 540, category: "Electronics" },
      { description: "Sony ZV-E10 ×3", brand: "Sony", unit_cost: 750, qty: 3, total: 2250, category: "Electronics" },
      { description: "Rode mics ×4", brand: "Rode", unit_cost: 170, qty: 4, total: 680, category: "Electronics" },
      { description: "Capture cards ×4", brand: "Elgato", unit_cost: 200, qty: 4, total: 800, category: "Electronics" },
      { description: "Stream Decks ×3", brand: "Elgato", unit_cost: 250, qty: 3, total: 750, category: "Electronics" },
      { description: "Mic arms ×4", brand: "Elgato", unit_cost: 95, qty: 4, total: 380, category: "Electronics" },
      { description: "LED panels ×8", brand: "Elgato", unit_cost: 120, qty: 8, total: 960, category: "Electronics" },
      { description: "Monitor arms ×3", brand: "Ergotron", unit_cost: 180, qty: 3, total: 540, category: "Electronics" },
      { description: "Teleprompter ×2", brand: "Parrot", unit_cost: 180, qty: 2, total: 360, category: "Electronics" },
      { description: "Backdrop stand system", brand: "Neewer", unit_cost: 85, qty: 3, total: 255, category: "Electronics" },
      { description: "Elgato Facecam Pro ×2", brand: "Elgato", unit_cost: 300, qty: 2, total: 600, category: "Electronics" },
    ],
  },
});

export const ORL_PC_A = tiered5({
  room: "Bedroom Orly",
  bundle_code: "ORL-PC-A",
  name: "Custom Computer Build",
  description: "Professional editing and production workstation",
  total_value: 4800,
  sweet_spot: false,
  plausibility: "easy",
  essential: {
    total: 1800,
    items: [
      { description: "Intel Core i7 13700K processor", brand: "Intel", unit_cost: 380, qty: 1, total: 380, category: "Electronics" },
      { description: "32GB DDR5 RAM Corsair", brand: "Corsair", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "NVIDIA RTX 4070 GPU", brand: "NVIDIA", unit_cost: 600, qty: 1, total: 600, category: "Electronics" },
      { description: "2TB NVMe SSD Samsung", brand: "Samsung", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "ATX case mid tower NZXT", brand: "NZXT", unit_cost: 120, qty: 1, total: 120, category: "Electronics" },
      { description: "850W power supply Corsair", brand: "Corsair", unit_cost: 130, qty: 1, total: 130, category: "Electronics" },
    ],
  },
  enhanced: {
    total: 3200,
    items: [
      { description: "Intel Core i9 13900K processor", brand: "Intel", unit_cost: 550, qty: 1, total: 550, category: "Electronics" },
      { description: "64GB DDR5 RAM", brand: "Corsair", unit_cost: 280, qty: 1, total: 280, category: "Electronics" },
      { description: "NVIDIA RTX 4080 GPU", brand: "NVIDIA", unit_cost: 1200, qty: 1, total: 1200, category: "Electronics" },
      { description: "4TB NVMe SSD ×2", brand: "Samsung", unit_cost: 280, qty: 2, total: 560, category: "Electronics" },
      { description: "Full tower case NZXT H9", brand: "NZXT", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "1000W PSU Corsair", brand: "Corsair", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "AIO liquid cooler 360mm", brand: "Corsair", unit_cost: 150, qty: 1, total: 150, category: "Electronics" },
    ],
  },
  complete: {
    total: 4800,
    items: [
      { description: "Intel Core i9 13900K", brand: "Intel", unit_cost: 550, qty: 1, total: 550, category: "Electronics" },
      { description: "128GB DDR5 RAM", brand: "Corsair", unit_cost: 480, qty: 1, total: 480, category: "Electronics" },
      { description: "NVIDIA RTX 4090 GPU", brand: "NVIDIA", unit_cost: 1600, qty: 1, total: 1600, category: "Electronics" },
      { description: "4TB NVMe SSDs ×3", brand: "Samsung", unit_cost: 280, qty: 3, total: 840, category: "Electronics" },
      { description: "Full tower case", brand: "NZXT", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
      { description: "1200W PSU", brand: "Corsair", unit_cost: 200, qty: 1, total: 200, category: "Electronics" },
      { description: "AIO cooler 360mm", brand: "Corsair", unit_cost: 150, qty: 1, total: 150, category: "Electronics" },
      { description: "Thunderbolt 4 expansion card", brand: "ASUS", unit_cost: 85, qty: 1, total: 85, category: "Electronics" },
      { description: "Internal SSD 8TB HDD backup", brand: "Seagate", unit_cost: 180, qty: 2, total: 360, category: "Electronics" },
    ],
  },
  full: {
    total: 7200,
    items: [
      { description: "AMD Threadripper Pro 5975WX", brand: "AMD", unit_cost: 1299, qty: 1, total: 1299, category: "Electronics" },
      { description: "128GB ECC DDR5", brand: "Corsair", unit_cost: 580, qty: 1, total: 580, category: "Electronics" },
      { description: "NVIDIA RTX 4090 ×2 SLI", brand: "NVIDIA", unit_cost: 1600, qty: 2, total: 3200, category: "Electronics" },
      { description: "NVMe SSDs 4TB ×4", brand: "Samsung", unit_cost: 280, qty: 4, total: 1120, category: "Electronics" },
      { description: "Professional workstation case", brand: "Fractal", unit_cost: 250, qty: 1, total: 250, category: "Electronics" },
      { description: "1600W PSU", brand: "Corsair", unit_cost: 350, qty: 1, total: 350, category: "Electronics" },
      { description: "AIO coolers ×2", brand: "Corsair", unit_cost: 150, qty: 2, total: 300, category: "Electronics" },
      { description: "RAID controller card", brand: "ASUS", unit_cost: 180, qty: 1, total: 180, category: "Electronics" },
    ],
  },
  ultimate: {
    total: 12000,
    items: [
      { description: "AMD Threadripper Pro workstation", brand: "AMD", unit_cost: 1299, qty: 2, total: 2598, category: "Electronics" },
      { description: "256GB ECC RAM", brand: "Corsair", unit_cost: 980, qty: 1, total: 980, category: "Electronics" },
      { description: "RTX 4090 GPUs ×2", brand: "NVIDIA", unit_cost: 1600, qty: 2, total: 3200, category: "Electronics" },
      { description: "4TB NVMe SSDs ×6", brand: "Samsung", unit_cost: 280, qty: 6, total: 1680, category: "Electronics" },
      { description: "Workstation cases ×2", brand: "Fractal", unit_cost: 250, qty: 2, total: 500, category: "Electronics" },
      { description: "1600W PSUs ×2", brand: "Corsair", unit_cost: 350, qty: 2, total: 700, category: "Electronics" },
      { description: "Custom water cooling loop", brand: "EKWB", unit_cost: 480, qty: 2, total: 960, category: "Electronics" },
      { description: "10GbE network card", brand: "ASUS", unit_cost: 120, qty: 2, total: 240, category: "Electronics" },
    ],
  },
});
