import { tiered5 } from "./bundles-five-tier-cumulative-helper";

export const GAR_SPORTS_A = tiered5({
  room: "Garage",
  bundle_code: "GAR-SPORTS-A",
  name: "Sports Memorabilia",
  description: "Mets, Raiders, Knicks collectibles for the garage",
  total_value: 7600,
  sweet_spot: false,
  plausibility: "easy",
  essential: {
    total: 1200,
    items: [
      { description: "Signed baseballs ×4", brand: "Rawlings", unit_cost: 120, qty: 4, total: 480, category: "Collectibles" },
      { description: "Signed basketball", brand: "Spalding", unit_cost: 280, qty: 1, total: 280, category: "Collectibles" },
      { description: "Signed Raiders football", brand: "Wilson", unit_cost: 280, qty: 1, total: 280, category: "Collectibles" },
    ],
  },
  enhanced: {
    total: 2400,
    items: [
      { description: "Signed baseballs ×6", brand: "Rawlings", unit_cost: 120, qty: 6, total: 720, category: "Collectibles" },
      { description: "Signed basketball ×2", brand: "Spalding", unit_cost: 280, qty: 2, total: 560, category: "Collectibles" },
      { description: "Signed footballs ×2", brand: "Wilson", unit_cost: 280, qty: 2, total: 560, category: "Collectibles" },
      { description: "UV display cases ×6", brand: "Ultra Pro", unit_cost: 85, qty: 6, total: 510, category: "Collectibles" },
      { description: "Team pennants ×6", brand: "", unit_cost: 45, qty: 6, total: 270, category: "Collectibles" },
    ],
  },
  complete: {
    total: 3600,
    items: [
      { description: "Signed baseballs ×8", brand: "Rawlings", unit_cost: 120, qty: 8, total: 960, category: "Collectibles" },
      { description: "Signed basketballs ×3", brand: "Spalding", unit_cost: 280, qty: 3, total: 840, category: "Collectibles" },
      { description: "Signed footballs ×3", brand: "Wilson", unit_cost: 280, qty: 3, total: 840, category: "Collectibles" },
      { description: "UV display cases ×10", brand: "Ultra Pro", unit_cost: 85, qty: 10, total: 850, category: "Collectibles" },
      { description: "Team pennants ×10", brand: "", unit_cost: 45, qty: 10, total: 450, category: "Collectibles" },
      { description: "Floating display shelves ×4", brand: "Custom Millwork", unit_cost: 120, qty: 4, total: 480, category: "Furniture" },
    ],
  },
  full: {
    total: 4800,
    items: [
      { description: "Signed baseballs ×12", brand: "Rawlings", unit_cost: 120, qty: 12, total: 1440, category: "Collectibles" },
      { description: "Signed basketballs ×4", brand: "Spalding", unit_cost: 280, qty: 4, total: 1120, category: "Collectibles" },
      { description: "Signed footballs ×4", brand: "Wilson", unit_cost: 280, qty: 4, total: 1120, category: "Collectibles" },
      { description: "UV display cases ×14", brand: "Ultra Pro", unit_cost: 85, qty: 14, total: 1190, category: "Collectibles" },
      { description: "Team pennants ×14", brand: "", unit_cost: 45, qty: 14, total: 630, category: "Collectibles" },
      { description: "Floating shelves ×6", brand: "Custom Millwork", unit_cost: 120, qty: 6, total: 720, category: "Furniture" },
      { description: "LED display lighting", brand: "Govee", unit_cost: 45, qty: 4, total: 180, category: "Electronics" },
    ],
  },
  ultimate: {
    total: 7600,
    items: [
      { description: "Signed baseballs ×18", brand: "Rawlings", unit_cost: 120, qty: 18, total: 2160, category: "Collectibles" },
      { description: "Signed basketballs ×6", brand: "Spalding", unit_cost: 280, qty: 6, total: 1680, category: "Collectibles" },
      { description: "Signed footballs ×6", brand: "Wilson", unit_cost: 280, qty: 6, total: 1680, category: "Collectibles" },
      { description: "UV cases ×20", brand: "Ultra Pro", unit_cost: 85, qty: 20, total: 1700, category: "Collectibles" },
      { description: "Team pennants ×20", brand: "", unit_cost: 45, qty: 20, total: 900, category: "Collectibles" },
      { description: "Display shelving wall unit", brand: "Restoration Hardware", unit_cost: 680, qty: 2, total: 1360, category: "Furniture" },
      { description: "LED lighting ×8", brand: "Govee", unit_cost: 45, qty: 8, total: 360, category: "Electronics" },
      { description: "Signed programs and magazines ×12", brand: "", unit_cost: 35, qty: 12, total: 420, category: "Collectibles" },
    ],
  },
});

export const GAR_BEACH_A = tiered5({
  room: "Garage",
  bundle_code: "GAR-BEACH-A",
  name: "Beach & Summer Activities",
  description: "Everything for Pacific Palisades beach and summer",
  total_value: 4800,
  sweet_spot: true,
  plausibility: "easy",
  essential: {
    total: 1200,
    items: [
      { description: "Beach umbrella UV protection large", brand: "Tommy Bahama", unit_cost: 85, qty: 2, total: 170, category: "Sports" },
      { description: "Beach chairs lightweight", brand: "Tommy Bahama", unit_cost: 65, qty: 4, total: 260, category: "Sports" },
      { description: "Cooler YETI Tundra 65", brand: "YETI", unit_cost: 380, qty: 1, total: 380, category: "Sports" },
      { description: "Beach towels oversized", brand: "Pendleton", unit_cost: 65, qty: 6, total: 390, category: "Textiles" },
      { description: "Sunscreen SPF 50 multi-pack", brand: "Supergoop", unit_cost: 35, qty: 6, total: 210, category: "Personal Care" },
    ],
  },
  enhanced: {
    total: 2400,
    items: [
      { description: "Beach umbrellas ×4", brand: "Tommy Bahama", unit_cost: 85, qty: 4, total: 340, category: "Sports" },
      { description: "Beach chairs ×8", brand: "Tommy Bahama", unit_cost: 65, qty: 8, total: 520, category: "Sports" },
      { description: "YETI Tundra 65 cooler", brand: "YETI", unit_cost: 380, qty: 1, total: 380, category: "Sports" },
      { description: "Beach towels oversized ×12", brand: "Pendleton", unit_cost: 65, qty: 12, total: 780, category: "Textiles" },
      { description: "Sunscreen packs ×12", brand: "Supergoop", unit_cost: 35, qty: 12, total: 420, category: "Personal Care" },
      { description: "Bocce ball set premium", brand: "GoSports", unit_cost: 45, qty: 2, total: 90, category: "Sports" },
      { description: "Volleyball net portable beach", brand: "Franklin", unit_cost: 85, qty: 1, total: 85, category: "Sports" },
      { description: "Frisbees disc golf set", brand: "Discraft", unit_cost: 25, qty: 4, total: 100, category: "Sports" },
      { description: "Snorkel sets adult", brand: "Cressi", unit_cost: 65, qty: 4, total: 260, category: "Sports" },
    ],
  },
  complete: {
    total: 3600,
    items: [
      { description: "Beach umbrellas ×6", brand: "Tommy Bahama", unit_cost: 85, qty: 6, total: 510, category: "Sports" },
      { description: "Beach chairs ×12", brand: "Tommy Bahama", unit_cost: 65, qty: 12, total: 780, category: "Sports" },
      { description: "YETI coolers ×2", brand: "YETI", unit_cost: 380, qty: 2, total: 760, category: "Sports" },
      { description: "Beach towels ×18", brand: "Pendleton", unit_cost: 65, qty: 18, total: 1170, category: "Textiles" },
      { description: "Sunscreen ×18", brand: "Supergoop", unit_cost: 35, qty: 18, total: 630, category: "Personal Care" },
      { description: "Bocce sets ×3", brand: "GoSports", unit_cost: 45, qty: 3, total: 135, category: "Sports" },
      { description: "Volleyball nets ×2", brand: "Franklin", unit_cost: 85, qty: 2, total: 170, category: "Sports" },
      { description: "Frisbee sets ×6", brand: "Discraft", unit_cost: 25, qty: 6, total: 150, category: "Sports" },
      { description: "Snorkel sets ×6", brand: "Cressi", unit_cost: 65, qty: 6, total: 390, category: "Sports" },
      { description: "Paddleball sets", brand: "GoSports", unit_cost: 35, qty: 4, total: 140, category: "Sports" },
      { description: "Beach bag canvas tote large", brand: "L.L. Bean", unit_cost: 45, qty: 6, total: 270, category: "Sports" },
      { description: "Waterproof phone cases", brand: "Lifeproof", unit_cost: 55, qty: 4, total: 220, category: "Electronics" },
    ],
  },
  full: {
    total: 4800,
    items: [
      { description: "Beach umbrellas ×8", brand: "Tommy Bahama", unit_cost: 85, qty: 8, total: 680, category: "Sports" },
      { description: "Beach chairs ×16", brand: "Tommy Bahama", unit_cost: 65, qty: 16, total: 1040, category: "Sports" },
      { description: "YETI coolers ×3", brand: "YETI", unit_cost: 380, qty: 3, total: 1140, category: "Sports" },
      { description: "Beach towels ×24", brand: "Pendleton", unit_cost: 65, qty: 24, total: 1560, category: "Textiles" },
      { description: "Sunscreen ×24", brand: "Supergoop", unit_cost: 35, qty: 24, total: 840, category: "Personal Care" },
      { description: "Bocce sets ×4", brand: "GoSports", unit_cost: 45, qty: 4, total: 180, category: "Sports" },
      { description: "Volleyball nets ×3", brand: "Franklin", unit_cost: 85, qty: 3, total: 255, category: "Sports" },
      { description: "Frisbee sets ×8", brand: "Discraft", unit_cost: 25, qty: 8, total: 200, category: "Sports" },
      { description: "Snorkel sets ×8", brand: "Cressi", unit_cost: 65, qty: 8, total: 520, category: "Sports" },
      { description: "Paddleball ×6", brand: "GoSports", unit_cost: 35, qty: 6, total: 210, category: "Sports" },
      { description: "Beach totes ×8", brand: "L.L. Bean", unit_cost: 45, qty: 8, total: 360, category: "Sports" },
      { description: "Waterproof phone cases ×6", brand: "Lifeproof", unit_cost: 55, qty: 6, total: 330, category: "Electronics" },
      { description: "Stand-up paddle boards", brand: "iSUP", unit_cost: 650, qty: 2, total: 1300, category: "Sports" },
    ],
  },
  ultimate: {
    total: 7500,
    items: [
      { description: "Beach umbrellas ×10", brand: "Tommy Bahama", unit_cost: 85, qty: 10, total: 850, category: "Sports" },
      { description: "Beach chairs ×20", brand: "Tommy Bahama", unit_cost: 65, qty: 20, total: 1300, category: "Sports" },
      { description: "YETI coolers ×4", brand: "YETI", unit_cost: 380, qty: 4, total: 1520, category: "Sports" },
      { description: "Beach towels ×30", brand: "Pendleton", unit_cost: 65, qty: 30, total: 1950, category: "Textiles" },
      { description: "Sunscreen ×30", brand: "Supergoop", unit_cost: 35, qty: 30, total: 1050, category: "Personal Care" },
      { description: "All beach game sets ×6", brand: "GoSports", unit_cost: 45, qty: 6, total: 270, category: "Sports" },
      { description: "Volleyball nets ×4", brand: "Franklin", unit_cost: 85, qty: 4, total: 340, category: "Sports" },
      { description: "Snorkel sets ×10", brand: "Cressi", unit_cost: 65, qty: 10, total: 650, category: "Sports" },
      { description: "Beach totes ×12", brand: "L.L. Bean", unit_cost: 45, qty: 12, total: 540, category: "Sports" },
      { description: "SUP boards ×3", brand: "iSUP", unit_cost: 650, qty: 3, total: 1950, category: "Sports" },
      { description: "Kayak inflatable tandem", brand: "Advanced Elements", unit_cost: 850, qty: 1, total: 850, category: "Sports" },
      { description: "Beach wagon folding utility", brand: "Mac Sports", unit_cost: 85, qty: 2, total: 170, category: "Sports" },
    ],
  },
});

export const GAR_CAMP_A = tiered5({
  room: "Garage",
  bundle_code: "GAR-CAMP-A",
  name: "Camping & Outdoor Adventure",
  description: "Complete camping gear for family adventures",
  total_value: 5800,
  sweet_spot: false,
  plausibility: "easy",
  essential: {
    total: 1400,
    items: [
      { description: "REI Co-op Kingdom 6 tent", brand: "REI Co-op", unit_cost: 580, qty: 1, total: 580, category: "Sports" },
      { description: "Sleeping bags REI Siesta 20", brand: "REI", unit_cost: 150, qty: 4, total: 600, category: "Sports" },
      { description: "Sleeping pads self-inflating", brand: "Therm-a-Rest", unit_cost: 85, qty: 4, total: 340, category: "Sports" },
      { description: "Camp chairs Helinox", brand: "Helinox", unit_cost: 180, qty: 2, total: 360, category: "Sports" },
    ],
  },
  enhanced: {
    total: 2800,
    items: [
      { description: "REI Kingdom 6 tent", brand: "REI Co-op", unit_cost: 580, qty: 1, total: 580, category: "Sports" },
      { description: "Sleeping bags ×4", brand: "REI", unit_cost: 150, qty: 4, total: 600, category: "Sports" },
      { description: "Sleeping pads ×4", brand: "Therm-a-Rest", unit_cost: 85, qty: 4, total: 340, category: "Sports" },
      { description: "Helinox chairs ×4", brand: "Helinox", unit_cost: 180, qty: 4, total: 720, category: "Sports" },
      { description: "Camp stove 2-burner MSR", brand: "MSR", unit_cost: 180, qty: 1, total: 180, category: "Sports" },
      { description: "Camp cookware set MSR", brand: "MSR", unit_cost: 85, qty: 1, total: 85, category: "Sports" },
      { description: "Headlamps Black Diamond ×4", brand: "Black Diamond", unit_cost: 45, qty: 4, total: 180, category: "Sports" },
      { description: "Camp lantern Goal Zero", brand: "Goal Zero", unit_cost: 120, qty: 2, total: 240, category: "Sports" },
      { description: "Water filter Sawyer", brand: "Sawyer", unit_cost: 35, qty: 2, total: 70, category: "Sports" },
    ],
  },
  complete: {
    total: 4200,
    items: [
      { description: "REI tents ×2", brand: "REI Co-op", unit_cost: 580, qty: 2, total: 1160, category: "Sports" },
      { description: "Sleeping bags ×6", brand: "REI", unit_cost: 150, qty: 6, total: 900, category: "Sports" },
      { description: "Sleeping pads ×6", brand: "Therm-a-Rest", unit_cost: 85, qty: 6, total: 510, category: "Sports" },
      { description: "Helinox chairs ×6", brand: "Helinox", unit_cost: 180, qty: 6, total: 1080, category: "Sports" },
      { description: "Camp stoves ×2", brand: "MSR", unit_cost: 180, qty: 2, total: 360, category: "Sports" },
      { description: "Cookware sets ×2", brand: "MSR", unit_cost: 85, qty: 2, total: 170, category: "Sports" },
      { description: "Headlamps ×6", brand: "Black Diamond", unit_cost: 45, qty: 6, total: 270, category: "Sports" },
      { description: "Goal Zero lanterns ×4", brand: "Goal Zero", unit_cost: 120, qty: 4, total: 480, category: "Sports" },
      { description: "Water filters ×4", brand: "Sawyer", unit_cost: 35, qty: 4, total: 140, category: "Sports" },
      { description: "Trekking poles Black Diamond ×2 pairs", brand: "Black Diamond", unit_cost: 120, qty: 2, total: 240, category: "Sports" },
      { description: "First aid kit REI comprehensive", brand: "REI", unit_cost: 45, qty: 3, total: 135, category: "Sports" },
      { description: "Camping table folding", brand: "Helinox", unit_cost: 180, qty: 2, total: 360, category: "Sports" },
    ],
  },
  full: {
    total: 5800,
    items: [
      { description: "Big Agnes tents ×2", brand: "Big Agnes", unit_cost: 680, qty: 2, total: 1360, category: "Sports" },
      { description: "Western Mountaineering sleeping bags ×4", brand: "Western Mountaineering", unit_cost: 380, qty: 4, total: 1520, category: "Sports" },
      { description: "Therm-a-Rest NeoAir pads ×6", brand: "Therm-a-Rest", unit_cost: 180, qty: 6, total: 1080, category: "Sports" },
      { description: "Helinox chairs ×8", brand: "Helinox", unit_cost: 180, qty: 8, total: 1440, category: "Sports" },
      { description: "Camp stoves ×3", brand: "MSR", unit_cost: 180, qty: 3, total: 540, category: "Sports" },
      { description: "Cookware ×3", brand: "MSR", unit_cost: 85, qty: 3, total: 255, category: "Sports" },
      { description: "Headlamps ×8", brand: "Black Diamond", unit_cost: 45, qty: 8, total: 360, category: "Sports" },
      { description: "Goal Zero power station", brand: "Goal Zero", unit_cost: 380, qty: 1, total: 380, category: "Electronics" },
      { description: "Water filters ×6", brand: "Sawyer", unit_cost: 35, qty: 6, total: 210, category: "Sports" },
      { description: "Trekking poles ×4 pairs", brand: "Black Diamond", unit_cost: 120, qty: 4, total: 480, category: "Sports" },
      { description: "First aid kits ×4", brand: "REI", unit_cost: 45, qty: 4, total: 180, category: "Sports" },
      { description: "Camp tables ×3", brand: "Helinox", unit_cost: 180, qty: 3, total: 540, category: "Sports" },
    ],
  },
  ultimate: {
    total: 9200,
    items: [
      { description: "Big Agnes tents ×3", brand: "Big Agnes", unit_cost: 680, qty: 3, total: 2040, category: "Sports" },
      { description: "Western Mountaineering bags ×6", brand: "Western Mountaineering", unit_cost: 380, qty: 6, total: 2280, category: "Sports" },
      { description: "NeoAir pads ×8", brand: "Therm-a-Rest", unit_cost: 180, qty: 8, total: 1440, category: "Sports" },
      { description: "Helinox chairs ×10", brand: "Helinox", unit_cost: 180, qty: 10, total: 1800, category: "Sports" },
      { description: "Camp stoves ×4", brand: "MSR", unit_cost: 180, qty: 4, total: 720, category: "Sports" },
      { description: "MSR cookware ×4", brand: "MSR", unit_cost: 85, qty: 4, total: 340, category: "Sports" },
      { description: "Black Diamond headlamps ×10", brand: "Black Diamond", unit_cost: 45, qty: 10, total: 450, category: "Sports" },
      { description: "Goal Zero power stations ×2", brand: "Goal Zero", unit_cost: 380, qty: 2, total: 760, category: "Electronics" },
      { description: "Solar panels Goal Zero", brand: "Goal Zero", unit_cost: 280, qty: 2, total: 560, category: "Electronics" },
      { description: "Trekking poles ×6 pairs", brand: "Black Diamond", unit_cost: 120, qty: 6, total: 720, category: "Sports" },
      { description: "First aid kits ×6", brand: "REI", unit_cost: 45, qty: 6, total: 270, category: "Sports" },
      { description: "Camp tables ×4", brand: "Helinox", unit_cost: 180, qty: 4, total: 720, category: "Sports" },
      { description: "Hammocks ENO ×4", brand: "ENO", unit_cost: 65, qty: 4, total: 260, category: "Sports" },
      { description: "Bear canisters ×4", brand: "BearVault", unit_cost: 80, qty: 4, total: 320, category: "Sports" },
    ],
  },
});

export const KIT_DOGS_A = tiered5({
  room: "Kitchen",
  bundle_code: "KIT-DOGS-A",
  name: "Dog Supplies & Accessories",
  description: "Complete supplies for two dogs in a luxury home",
  total_value: 3200,
  sweet_spot: true,
  plausibility: "easy",
  essential: {
    total: 800,
    items: [
      { description: "Dog beds memory foam large", brand: "Casper", unit_cost: 185, qty: 2, total: 370, category: "Pet" },
      { description: "Stainless steel dog bowls set", brand: "Yeti", unit_cost: 45, qty: 2, total: 90, category: "Pet" },
      { description: "Dog leashes leather premium", brand: "Filson", unit_cost: 65, qty: 2, total: 130, category: "Pet" },
      { description: "Dog collars leather premium", brand: "Filson", unit_cost: 45, qty: 2, total: 90, category: "Pet" },
    ],
  },
  enhanced: {
    total: 1600,
    items: [
      { description: "Casper dog beds ×2", brand: "Casper", unit_cost: 185, qty: 2, total: 370, category: "Pet" },
      { description: "Yeti dog bowls ×2 sets", brand: "Yeti", unit_cost: 45, qty: 2, total: 90, category: "Pet" },
      { description: "Leather leashes ×2", brand: "Filson", unit_cost: 65, qty: 2, total: 130, category: "Pet" },
      { description: "Leather collars ×2", brand: "Filson", unit_cost: 45, qty: 2, total: 90, category: "Pet" },
      { description: "Dog crate airline approved", brand: "Petmate", unit_cost: 120, qty: 2, total: 240, category: "Pet" },
      { description: "Dog toys premium set", brand: "West Paw", unit_cost: 35, qty: 4, total: 140, category: "Pet" },
      { description: "Dog grooming kit professional", brand: "Wahl", unit_cost: 85, qty: 1, total: 85, category: "Pet" },
      { description: "Dog gates retractable ×2", brand: "Qdos", unit_cost: 120, qty: 2, total: 240, category: "Pet" },
    ],
  },
  complete: {
    total: 2400,
    items: [
      { description: "Casper dog beds ×4", brand: "Casper", unit_cost: 185, qty: 4, total: 740, category: "Pet" },
      { description: "Yeti dog bowls ×4", brand: "Yeti", unit_cost: 45, qty: 4, total: 180, category: "Pet" },
      { description: "Leather leashes ×4", brand: "Filson", unit_cost: 65, qty: 4, total: 260, category: "Pet" },
      { description: "Leather collars ×4", brand: "Filson", unit_cost: 45, qty: 4, total: 180, category: "Pet" },
      { description: "Airline crates ×2", brand: "Petmate", unit_cost: 120, qty: 2, total: 240, category: "Pet" },
      { description: "Dog toy sets ×6", brand: "West Paw", unit_cost: 35, qty: 6, total: 210, category: "Pet" },
      { description: "Grooming kit", brand: "Wahl", unit_cost: 85, qty: 1, total: 85, category: "Pet" },
      { description: "Dog gates ×4", brand: "Qdos", unit_cost: 120, qty: 4, total: 480, category: "Pet" },
      { description: "P.L.A.Y. luxury dog beds ×2", brand: "P.L.A.Y.", unit_cost: 180, qty: 2, total: 360, category: "Pet" },
      { description: "Dog backpacks hiking", brand: "Ruffwear", unit_cost: 95, qty: 2, total: 190, category: "Pet" },
      { description: "Dog life jackets", brand: "Ruffwear", unit_cost: 85, qty: 2, total: 170, category: "Pet" },
    ],
  },
  full: {
    total: 3200,
    items: [
      { description: "Casper dog beds ×6", brand: "Casper", unit_cost: 185, qty: 6, total: 1110, category: "Pet" },
      { description: "Yeti dog bowls ×6", brand: "Yeti", unit_cost: 45, qty: 6, total: 270, category: "Pet" },
      { description: "Leather leashes ×6", brand: "Filson", unit_cost: 65, qty: 6, total: 390, category: "Pet" },
      { description: "Leather collars ×6", brand: "Filson", unit_cost: 45, qty: 6, total: 270, category: "Pet" },
      { description: "Airline crates ×4", brand: "Petmate", unit_cost: 120, qty: 4, total: 480, category: "Pet" },
      { description: "Dog toys ×8", brand: "West Paw", unit_cost: 35, qty: 8, total: 280, category: "Pet" },
      { description: "Grooming kits ×2", brand: "Wahl", unit_cost: 85, qty: 2, total: 170, category: "Pet" },
      { description: "Dog gates ×6", brand: "Qdos", unit_cost: 120, qty: 6, total: 720, category: "Pet" },
      { description: "P.L.A.Y. beds ×4", brand: "P.L.A.Y.", unit_cost: 180, qty: 4, total: 720, category: "Pet" },
      { description: "Ruffwear backpacks ×2", brand: "Ruffwear", unit_cost: 95, qty: 2, total: 190, category: "Pet" },
      { description: "Dog life jackets ×2", brand: "Ruffwear", unit_cost: 85, qty: 2, total: 170, category: "Pet" },
      { description: "Automatic dog feeder smart", brand: "Petlibro", unit_cost: 120, qty: 2, total: 240, category: "Pet" },
      { description: "Dog training treats supply", brand: "Zuke", unit_cost: 18, qty: 12, total: 216, category: "Pet" },
    ],
  },
  ultimate: {
    total: 4800,
    items: [
      { description: "Casper dog beds ×8", brand: "Casper", unit_cost: 185, qty: 8, total: 1480, category: "Pet" },
      { description: "Yeti bowls ×8", brand: "Yeti", unit_cost: 45, qty: 8, total: 360, category: "Pet" },
      { description: "Leather gear ×8", brand: "Filson", unit_cost: 65, qty: 8, total: 520, category: "Pet" },
      { description: "Airline crates ×4", brand: "Petmate", unit_cost: 120, qty: 4, total: 480, category: "Pet" },
      { description: "Dog toys ×12", brand: "West Paw", unit_cost: 35, qty: 12, total: 420, category: "Pet" },
      { description: "Grooming kits ×3", brand: "Wahl", unit_cost: 85, qty: 3, total: 255, category: "Pet" },
      { description: "Dog gates ×8", brand: "Qdos", unit_cost: 120, qty: 8, total: 960, category: "Pet" },
      { description: "P.L.A.Y. luxury beds ×6", brand: "P.L.A.Y.", unit_cost: 180, qty: 6, total: 1080, category: "Pet" },
      { description: "Ruffwear gear sets ×2", brand: "Ruffwear", unit_cost: 95, qty: 4, total: 380, category: "Pet" },
      { description: "Smart feeders ×4", brand: "Petlibro", unit_cost: 120, qty: 4, total: 480, category: "Pet" },
      { description: "Dog camera treat dispenser", brand: "Furbo", unit_cost: 180, qty: 2, total: 360, category: "Pet" },
      { description: "Dog DNA test kits", brand: "Embark", unit_cost: 120, qty: 2, total: 240, category: "Pet" },
    ],
  },
});
