import { tiered5 } from "./bundles-five-tier-cumulative-helper";

/** Sports Memorabilia — cumulative tiers (David Office / Guest Room). */
export const DAV_SPORTS_A = tiered5({
  room: "David Office / Guest Room",
  bundle_code: "DAV-SPORTS-A",
  name: "Sports Memorabilia Collection",
  description: "Mets, Raiders, Knicks signed collectibles and memorabilia",
  total_value: 12900,
  sweet_spot: false,
  plausibility: "easy",
  essential: {
    total: 1800,
    items: [
      { description: "Signed baseball MLB authenticated", brand: "Rawlings", unit_cost: 120, qty: 3, total: 360, category: "Collectibles" },
      { description: "NY Mets signed jersey framed", brand: "Fanatics", unit_cost: 380, qty: 1, total: 380, category: "Collectibles" },
      { description: "NY Knicks signed basketball", brand: "Spalding", unit_cost: 280, qty: 1, total: 280, category: "Collectibles" },
      { description: "Las Vegas Raiders signed mini helmet", brand: "Riddell", unit_cost: 180, qty: 1, total: 180, category: "Collectibles" },
    ],
  },
  enhanced: {
    total: 3800,
    items: [
      { description: "Signed MLB baseballs ×3", brand: "Rawlings", unit_cost: 120, qty: 3, total: 360, category: "Collectibles" },
      { description: "NY Mets signed jersey framed", brand: "Fanatics", unit_cost: 380, qty: 2, total: 760, category: "Collectibles" },
      { description: "NY Knicks signed basketball", brand: "Spalding", unit_cost: 280, qty: 1, total: 280, category: "Collectibles" },
      { description: "Raiders signed mini helmet", brand: "Riddell", unit_cost: 180, qty: 2, total: 360, category: "Collectibles" },
      { description: "Mets game-used bat authenticated", brand: "Louisville Slugger", unit_cost: 280, qty: 1, total: 280, category: "Collectibles" },
      { description: "Knicks signed photograph framed 16x20", brand: "Steiner Sports", unit_cost: 220, qty: 2, total: 440, category: "Collectibles" },
      { description: "Raiders authentic game jersey", brand: "Wilson", unit_cost: 380, qty: 1, total: 380, category: "Collectibles" },
    ],
  },
  complete: {
    total: 5800,
    items: [
      { description: "Signed MLB baseballs ×6", brand: "Rawlings", unit_cost: 120, qty: 6, total: 720, category: "Collectibles" },
      { description: "Mets signed jerseys framed ×3", brand: "Fanatics", unit_cost: 380, qty: 3, total: 1140, category: "Collectibles" },
      { description: "Knicks signed basketball ×2", brand: "Spalding", unit_cost: 280, qty: 2, total: 560, category: "Collectibles" },
      { description: "Raiders mini helmet signed ×3", brand: "Riddell", unit_cost: 180, qty: 3, total: 540, category: "Collectibles" },
      { description: "Mets game-used bat ×2", brand: "Louisville Slugger", unit_cost: 280, qty: 2, total: 560, category: "Collectibles" },
      { description: "Knicks signed photos framed ×4", brand: "Steiner Sports", unit_cost: 220, qty: 4, total: 880, category: "Collectibles" },
      { description: "Raiders game jersey ×2", brand: "Wilson", unit_cost: 380, qty: 2, total: 760, category: "Collectibles" },
      { description: "UV display cases for memorabilia", brand: "Ultra Pro", unit_cost: 85, qty: 6, total: 510, category: "Collectibles" },
      { description: "Mets pennants vintage", brand: "", unit_cost: 45, qty: 6, total: 270, category: "Collectibles" },
      { description: "Knicks pennants vintage", brand: "", unit_cost: 45, qty: 4, total: 180, category: "Collectibles" },
    ],
  },
  full: {
    total: 8700,
    items: [
      { description: "Signed baseballs ×10", brand: "Rawlings", unit_cost: 120, qty: 10, total: 1200, category: "Collectibles" },
      { description: "Mets jerseys framed ×4", brand: "Fanatics", unit_cost: 380, qty: 4, total: 1520, category: "Collectibles" },
      { description: "Knicks basketballs signed ×3", brand: "Spalding", unit_cost: 280, qty: 3, total: 840, category: "Collectibles" },
      { description: "Raiders helmets signed ×4", brand: "Riddell", unit_cost: 180, qty: 4, total: 720, category: "Collectibles" },
      { description: "Mets game bats ×3", brand: "Louisville Slugger", unit_cost: 280, qty: 3, total: 840, category: "Collectibles" },
      { description: "Signed photos framed ×6", brand: "Steiner Sports", unit_cost: 220, qty: 6, total: 1320, category: "Collectibles" },
      { description: "Raiders jerseys ×3", brand: "Wilson", unit_cost: 380, qty: 3, total: 1140, category: "Collectibles" },
      { description: "UV display cases ×12", brand: "Ultra Pro", unit_cost: 85, qty: 12, total: 1020, category: "Collectibles" },
      { description: "Team pennants ×12", brand: "", unit_cost: 45, qty: 12, total: 540, category: "Collectibles" },
      { description: "Commemorative programs ×8", brand: "", unit_cost: 35, qty: 8, total: 280, category: "Collectibles" },
      { description: "Display wall shelving unit", brand: "Restoration Hardware", unit_cost: 680, qty: 1, total: 680, category: "Furniture" },
    ],
  },
  ultimate: {
    total: 12900,
    items: [
      { description: "Signed baseballs ×15", brand: "Rawlings", unit_cost: 120, qty: 15, total: 1800, category: "Collectibles" },
      { description: "Mets jerseys framed ×6", brand: "Fanatics", unit_cost: 380, qty: 6, total: 2280, category: "Collectibles" },
      { description: "Knicks basketballs ×4", brand: "Spalding", unit_cost: 280, qty: 4, total: 1120, category: "Collectibles" },
      { description: "Raiders helmets ×6", brand: "Riddell", unit_cost: 180, qty: 6, total: 1080, category: "Collectibles" },
      { description: "Game bats ×4", brand: "Louisville Slugger", unit_cost: 280, qty: 4, total: 1120, category: "Collectibles" },
      { description: "Signed photos ×10", brand: "Steiner Sports", unit_cost: 220, qty: 10, total: 2200, category: "Collectibles" },
      { description: "Team jerseys ×5", brand: "Wilson", unit_cost: 380, qty: 5, total: 1900, category: "Collectibles" },
      { description: "UV display cases ×18", brand: "Ultra Pro", unit_cost: 85, qty: 18, total: 1530, category: "Collectibles" },
      { description: "Team pennants ×18", brand: "", unit_cost: 45, qty: 18, total: 810, category: "Collectibles" },
      { description: "Display shelving units ×2", brand: "Restoration Hardware", unit_cost: 680, qty: 2, total: 1360, category: "Furniture" },
      { description: "LED display lighting strips", brand: "Govee", unit_cost: 45, qty: 6, total: 270, category: "Electronics" },
      { description: "Signed football Raiders authenticated", brand: "Wilson", unit_cost: 280, qty: 2, total: 560, category: "Collectibles" },
    ],
  },
});

/** Japanese Tea Room — cumulative tiers. */
export const DAV_TEA_A = tiered5({
  room: "David Office / Guest Room",
  bundle_code: "DAV-TEA-A",
  name: "Japanese Tea Room Setup",
  description: "Wabi-sabi inspired tea ceremony collection",
  total_value: 4800,
  sweet_spot: true,
  plausibility: "easy",
  essential: {
    total: 1200,
    items: [
      { description: "Tetsubin cast iron teapot Japanese", brand: "Iwachu", unit_cost: 180, qty: 1, total: 180, category: "Kitchen" },
      { description: "Matcha whisk set bamboo", brand: "Ippodo", unit_cost: 45, qty: 2, total: 90, category: "Kitchen" },
      { description: "Handcrafted ceramic tea bowls chawan", brand: "", unit_cost: 85, qty: 4, total: 340, category: "Kitchen" },
      { description: "Japanese herbal tea selection assorted", brand: "Harney & Sons", unit_cost: 28, qty: 6, total: 168, category: "Kitchen" },
      { description: "Bamboo tea tray", brand: "", unit_cost: 65, qty: 1, total: 65, category: "Kitchen" },
    ],
  },
  enhanced: {
    total: 2800,
    items: [
      { description: "Tetsubin cast iron teapot", brand: "Iwachu", unit_cost: 180, qty: 1, total: 180, category: "Kitchen" },
      { description: "Matcha whisk set", brand: "Ippodo", unit_cost: 45, qty: 2, total: 90, category: "Kitchen" },
      { description: "Handcrafted chawan tea bowls", brand: "", unit_cost: 85, qty: 4, total: 340, category: "Kitchen" },
      { description: "Japanese herbal tea selection", brand: "Harney & Sons", unit_cost: 28, qty: 6, total: 168, category: "Kitchen" },
      { description: "Bamboo tea tray", brand: "", unit_cost: 65, qty: 1, total: 65, category: "Kitchen" },
      { description: "Low Japanese tea table chabudai", brand: "", unit_cost: 380, qty: 1, total: 380, category: "Furniture" },
      { description: "Floor sitting cushions zabuton", brand: "", unit_cost: 95, qty: 4, total: 380, category: "Furniture" },
      { description: "Porcelain tea cups yunomi set of 6", brand: "", unit_cost: 65, qty: 1, total: 65, category: "Kitchen" },
    ],
  },
  complete: {
    total: 4800,
    items: [
      { description: "Tetsubin cast iron teapot", brand: "Iwachu", unit_cost: 180, qty: 2, total: 360, category: "Kitchen" },
      { description: "Matcha whisk set", brand: "Ippodo", unit_cost: 45, qty: 4, total: 180, category: "Kitchen" },
      { description: "Handcrafted chawan tea bowls", brand: "", unit_cost: 85, qty: 8, total: 680, category: "Kitchen" },
      { description: "Japanese herbal tea selection", brand: "Harney & Sons", unit_cost: 28, qty: 12, total: 336, category: "Kitchen" },
      { description: "Bamboo tea trays", brand: "", unit_cost: 65, qty: 2, total: 130, category: "Kitchen" },
      { description: "Low Japanese tea table chabudai", brand: "", unit_cost: 380, qty: 1, total: 380, category: "Furniture" },
      { description: "Floor cushions zabuton", brand: "", unit_cost: 95, qty: 6, total: 570, category: "Furniture" },
      { description: "Yunomi tea cups set of 6", brand: "", unit_cost: 65, qty: 2, total: 130, category: "Kitchen" },
      { description: "Kyusu teapot clay side handle", brand: "", unit_cost: 120, qty: 2, total: 240, category: "Kitchen" },
      { description: "Premium matcha powder ceremonial grade", brand: "Ippodo", unit_cost: 38, qty: 6, total: 228, category: "Kitchen" },
      { description: "Bamboo matcha scoop chashaku", brand: "", unit_cost: 12, qty: 6, total: 72, category: "Kitchen" },
      { description: "Tea storage canisters washi paper", brand: "", unit_cost: 28, qty: 6, total: 168, category: "Kitchen" },
    ],
  },
  full: {
    total: 7200,
    items: [
      { description: "Tetsubin teapots", brand: "Iwachu", unit_cost: 180, qty: 3, total: 540, category: "Kitchen" },
      { description: "Matcha whisk sets", brand: "Ippodo", unit_cost: 45, qty: 6, total: 270, category: "Kitchen" },
      { description: "Chawan tea bowls handcrafted", brand: "", unit_cost: 85, qty: 12, total: 1020, category: "Kitchen" },
      { description: "Japanese herbal teas assorted", brand: "Harney & Sons", unit_cost: 28, qty: 20, total: 560, category: "Kitchen" },
      { description: "Bamboo tea trays", brand: "", unit_cost: 65, qty: 3, total: 195, category: "Kitchen" },
      { description: "Low tea table chabudai", brand: "", unit_cost: 380, qty: 1, total: 380, category: "Furniture" },
      { description: "Zabuton floor cushions", brand: "", unit_cost: 95, qty: 8, total: 760, category: "Furniture" },
      { description: "Yunomi cups ×12", brand: "", unit_cost: 65, qty: 2, total: 130, category: "Kitchen" },
      { description: "Kyusu teapots ×3", brand: "", unit_cost: 120, qty: 3, total: 360, category: "Kitchen" },
      { description: "Ceremonial matcha powder", brand: "Ippodo", unit_cost: 38, qty: 12, total: 456, category: "Kitchen" },
      { description: "Bamboo chasaku scoops", brand: "", unit_cost: 12, qty: 12, total: 144, category: "Kitchen" },
      { description: "Washi tea canisters", brand: "", unit_cost: 28, qty: 12, total: 336, category: "Kitchen" },
      { description: "Tokonoma alcove scroll painting", brand: "", unit_cost: 280, qty: 1, total: 280, category: "Decorative" },
      { description: "Ikebana flower arranging vase", brand: "", unit_cost: 120, qty: 2, total: 240, category: "Decorative" },
      { description: "Japanese incense set kodo", brand: "Baieido", unit_cost: 45, qty: 4, total: 180, category: "Decorative" },
    ],
  },
  ultimate: {
    total: 11000,
    items: [
      { description: "Tetsubin teapots", brand: "Iwachu", unit_cost: 180, qty: 4, total: 720, category: "Kitchen" },
      { description: "Matcha whisk sets", brand: "Ippodo", unit_cost: 45, qty: 8, total: 360, category: "Kitchen" },
      { description: "Chawan bowls handcrafted", brand: "", unit_cost: 85, qty: 16, total: 1360, category: "Kitchen" },
      { description: "Japanese teas", brand: "Harney & Sons", unit_cost: 28, qty: 30, total: 840, category: "Kitchen" },
      { description: "Low tea table", brand: "", unit_cost: 380, qty: 2, total: 760, category: "Furniture" },
      { description: "Zabuton cushions", brand: "", unit_cost: 95, qty: 10, total: 950, category: "Furniture" },
      { description: "Yunomi cups", brand: "", unit_cost: 65, qty: 4, total: 260, category: "Kitchen" },
      { description: "Kyusu teapots", brand: "", unit_cost: 120, qty: 4, total: 480, category: "Kitchen" },
      { description: "Matcha powder", brand: "Ippodo", unit_cost: 38, qty: 18, total: 684, category: "Kitchen" },
      { description: "Tokonoma scroll", brand: "", unit_cost: 280, qty: 2, total: 560, category: "Decorative" },
      { description: "Ikebana vases", brand: "", unit_cost: 120, qty: 4, total: 480, category: "Decorative" },
      { description: "Japanese incense", brand: "Baieido", unit_cost: 45, qty: 8, total: 360, category: "Decorative" },
      { description: "Shoji screen room divider", brand: "", unit_cost: 380, qty: 2, total: 760, category: "Furniture" },
      { description: "Bonsai tree decorative", brand: "", unit_cost: 180, qty: 3, total: 540, category: "Decorative" },
      { description: "Tatami floor mat", brand: "", unit_cost: 220, qty: 2, total: 440, category: "Furniture" },
    ],
  },
});
