import type { Bundle, BundleItem } from "./bundles-data";

function item(
  description: string,
  brand: string,
  qty: number,
  unit_cost: number,
  category: string
): BundleItem {
  return { description, brand, qty, unit_cost, total: qty * unit_cost, category };
}

function sumItems(items: BundleItem[]): number {
  return items.reduce((s, i) => s + i.total, 0);
}

function bundle(
  partial: Omit<Bundle, "items" | "total_value"> & { items: BundleItem[] }
): Bundle {
  const total_value = sumItems(partial.items);
  return { ...partial, total_value };
}

/** $5K–$40K focused packages — listed first in UI (tier: affordable). */
export const AFFORDABLE_BUNDLES: Bundle[] = [
  bundle({
    room: "Living Room",
    bundle_code: "LR-LIGHT-A",
    name: "Lighting Refresh",
    description: "Update lighting throughout the living room",
    tier: "affordable",
    sweet_spot: false,
    plausibility: "easy",
    items: [
      item("Apparatus Studio Signal X floor lamp", "Apparatus Studio", 1, 8000, "Lighting"),
      item("Arteriors brass table lamp pair", "Arteriors", 1, 1800, "Lighting"),
      item("Visual Comfort table lamp", "Visual Comfort", 1, 1200, "Lighting"),
      item("Dimmer switches smart Lutron", "Lutron", 4, 180, "Electronics"),
    ],
  }),
  bundle({
    room: "Living Room",
    bundle_code: "LR-TEXTILE-A",
    name: "Textiles & Soft Goods",
    description: "Refresh pillows, throws, and window treatments",
    tier: "affordable",
    sweet_spot: false,
    plausibility: "easy",
    items: [
      item("Rogers & Goffigon linen drapes pair", "Rogers & Goffigon", 1, 3800, "Textiles"),
      item("Sferra throw blanket cashmere", "Sferra", 2, 680, "Textiles"),
      item("Down alternative throw pillows", "Parachute", 8, 120, "Textiles"),
      item("Lumbar pillows decorative", "Society6", 6, 85, "Textiles"),
      item("The Shade Store roman shades", "The Shade Store", 2, 850, "Textiles"),
    ],
  }),
  bundle({
    room: "Living Room",
    bundle_code: "LR-ENTERTAIN-A",
    name: "Entertaining Essentials",
    description: "Bar cart and entertaining setup",
    tier: "affordable",
    sweet_spot: false,
    plausibility: "easy",
    items: [
      item("Brass bar cart with shelves", "CB2", 1, 1200, "Furniture"),
      item("Riedel wine glasses set of 8", "Riedel", 1, 320, "Kitchen"),
      item("Cocktail shaker set stainless", "Crafthouse", 1, 280, "Kitchen"),
      item("Ice bucket stainless double-wall", "Rabbit", 1, 85, "Kitchen"),
      item("Decanter crystal whiskey", "Waterford", 2, 180, "Kitchen"),
      item("Cocktail glasses crystal set of 8", "Waterford", 1, 240, "Kitchen"),
      item("Serving trays lacquer large", "Hawkins New York", 2, 180, "Decorative"),
    ],
  }),
  bundle({
    room: "Living Room",
    bundle_code: "LR-DECOR-A",
    name: "Art & Decorative Objects",
    description: "Decorative objects and accent pieces",
    tier: "affordable",
    sweet_spot: false,
    plausibility: "easy",
    items: [
      item("Heath Ceramics large vessel", "Heath Ceramics", 3, 380, "Decorative"),
      item("Marble bookends pair", "", 2, 180, "Decorative"),
      item("Ceramic table sculpture", "", 2, 450, "Decorative"),
      item("Coffee table books Assouline", "Assouline", 6, 85, "Books"),
      item("Decorative trays marble", "", 3, 220, "Decorative"),
      item("Woven baskets set of 3", "", 2, 280, "Decorative"),
    ],
  }),
  bundle({
    room: "Kitchen",
    bundle_code: "KIT-COOKWARE-A",
    name: "Premium Cookware Upgrade",
    description: "Upgrade to professional grade cookware",
    tier: "affordable",
    sweet_spot: true,
    plausibility: "easy",
    items: [
      item("Mauviel M'Cook 10-piece cookware set", "Mauviel", 1, 2800, "Kitchen"),
      item("Staub cast iron set 3-piece", "Staub", 1, 680, "Kitchen"),
      item("Demeyere Atlantis saucepan set", "Demeyere", 1, 980, "Kitchen"),
      item("Miyabi Birchwood knife set 7-piece", "Miyabi", 1, 1200, "Kitchen"),
      item("Boos walnut butcher block 24x18", "John Boos", 1, 380, "Kitchen"),
    ],
  }),
  bundle({
    room: "Kitchen",
    bundle_code: "KIT-TABLE-A",
    name: "Table Setting for 12",
    description: "Complete table service for entertaining",
    tier: "affordable",
    sweet_spot: false,
    plausibility: "easy",
    items: [
      item("Dinner plates ceramic set of 12", "East Fork", 12, 48, "Kitchen"),
      item("Salad plates set of 12", "East Fork", 12, 42, "Kitchen"),
      item("Soup bowls set of 12", "East Fork", 12, 42, "Kitchen"),
      item("Linen napkins set of 12", "Hawkins New York", 12, 18, "Kitchen"),
      item("Silverware set Christofle 12-place", "Christofle", 1, 1800, "Kitchen"),
      item("Water glasses crystal set of 12", "Riedel", 1, 180, "Kitchen"),
    ],
  }),
  bundle({
    room: "Kitchen",
    bundle_code: "KIT-BAR-A",
    name: "Wine & Bar Collection",
    description: "Wine and spirits for a well-stocked kitchen",
    tier: "affordable",
    sweet_spot: true,
    plausibility: "easy",
    items: [
      item("Red wine collection 24 bottles", "", 24, 45, "Kitchen"),
      item("White wine collection 12 bottles", "", 12, 35, "Kitchen"),
      item("Champagne bottles 6 pack", "", 6, 65, "Kitchen"),
      item("Premium spirits whiskey scotch bourbon", "", 6, 85, "Kitchen"),
      item("Wine rack wall mounted 30 bottle", "Vinotemp", 1, 380, "Furniture"),
    ],
  }),
  bundle({
    room: "Bedroom Orly",
    bundle_code: "ORL-PHOTO-A",
    name: "Photography Studio Setup",
    description: "Professional photography lighting and grip",
    tier: "affordable",
    sweet_spot: true,
    plausibility: "easy",
    items: [
      item("Aputure 300d II LED light", "Aputure", 1, 1099, "Electronics"),
      item("Aputure light dome softbox", "Aputure", 2, 180, "Electronics"),
      item("C-stand heavy duty light stand", "Matthews", 2, 180, "Electronics"),
      item("Sony 24-70mm GM lens", "Sony", 1, 2299, "Electronics"),
      item("Sony 85mm GM portrait lens", "Sony", 1, 1799, "Electronics"),
    ],
  }),
  bundle({
    room: "Bedroom Orly",
    bundle_code: "ORL-AUDIO-A",
    name: "Audio Production Setup",
    description: "Professional audio gear for filmmaking",
    tier: "affordable",
    sweet_spot: false,
    plausibility: "easy",
    items: [
      item("Rode NTG5 shotgun microphone", "Rode", 1, 500, "Electronics"),
      item("Sound Devices MixPre-3 audio recorder", "Sound Devices", 1, 699, "Electronics"),
      item("Sennheiser wireless lav system", "Sennheiser", 1, 850, "Electronics"),
      item("Boom pole carbon fiber", "K-Tek", 1, 380, "Electronics"),
      item("Headphone amplifier desktop", "Schiit", 1, 200, "Electronics"),
    ],
  }),
  bundle({
    room: "Bedroom Rafe",
    bundle_code: "RAF-DISPLAY-A",
    name: "Memorabilia Display Setup",
    description: "Professional display for sports memorabilia",
    tier: "affordable",
    sweet_spot: true,
    plausibility: "easy",
    items: [
      item("UV-protected jersey display frame", "Steiner Sports", 6, 380, "Decorative"),
      item("Floating wall shelves for memorabilia", "West Elm", 4, 180, "Furniture"),
      item("LED display lighting strip", "Govee", 4, 45, "Electronics"),
    ],
  }),
  bundle({
    room: "Bedroom Rafe",
    bundle_code: "RAF-CLOSET-A",
    name: "Luxury Closet System",
    description: "Organization system for streetwear collection",
    tier: "affordable",
    sweet_spot: false,
    plausibility: "easy",
    items: [
      item("Custom closet system modular", "California Closets", 1, 2400, "Furniture"),
      item("Shoe shelving tower 20-pair", "The Container Store", 1, 380, "Furniture"),
      item("Hat display rack wall mount", "", 2, 180, "Furniture"),
      item("Velvet hangers 100-pack", "Zober", 4, 28, "Consumables"),
    ],
  }),
  bundle({
    room: "David Office / Guest Room",
    bundle_code: "DAV-TECH-A",
    name: "Professional AV Setup",
    description: "Filmmaker home office AV and tech",
    tier: "affordable",
    sweet_spot: true,
    plausibility: "easy",
    items: [
      item("Sony 65in Bravia XR OLED TV", "Sony", 1, 2799, "Electronics"),
      item("Sonos Arc soundbar", "Sonos", 1, 899, "Electronics"),
      item("Apple Mac Studio M2 Max", "Apple", 1, 1999, "Electronics"),
      item("LG UltraFine 5K display", "LG", 1, 1299, "Electronics"),
      item("Elgato Stream Deck XL", "Elgato", 1, 250, "Electronics"),
      item("iPad Pro 12.9in M2", "Apple", 1, 1099, "Electronics"),
    ],
  }),
  bundle({
    room: "David Office / Guest Room",
    bundle_code: "DAV-GUEST-A",
    name: "Guest Room Setup",
    description: "Complete guest bedroom essentials",
    tier: "affordable",
    sweet_spot: false,
    plausibility: "easy",
    items: [
      item("Parachute percale sheet set queen", "Parachute", 2, 199, "Textiles"),
      item("Down alternative duvet insert queen", "Parachute", 1, 180, "Textiles"),
      item("Duvet cover linen queen", "Parachute", 1, 199, "Textiles"),
      item("Euro shams set of 2", "Parachute", 2, 99, "Textiles"),
      item("Throw blanket cashmere", "Sferra", 1, 380, "Textiles"),
      item("Bedside table lamp", "Visual Comfort", 2, 480, "Lighting"),
    ],
  }),
  bundle({
    room: "Garage",
    bundle_code: "GAR-BIKE-A",
    name: "Cycling Upgrade Pack",
    description: "Premium cycling gear and accessories",
    tier: "affordable",
    sweet_spot: true,
    plausibility: "easy",
    items: [
      item("Specialized S-Works road helmet", "Specialized", 2, 280, "Sports"),
      item("Rapha Pro Team bib shorts", "Rapha", 3, 220, "Sports"),
      item("Rapha Pro Team jersey", "Rapha", 3, 185, "Sports"),
      item("Shimano Dura-Ace cycling shoes", "Shimano", 2, 380, "Sports"),
      item("Garmin Edge 1040 cycling computer", "Garmin", 2, 599, "Electronics"),
      item("Wahoo KICKR smart trainer", "Wahoo", 1, 1200, "Sports"),
    ],
  }),
  bundle({
    room: "Garage",
    bundle_code: "GAR-SURF-A",
    name: "Surf Quiver Upgrade",
    description: "Premium surfboard quiver and gear",
    tier: "affordable",
    sweet_spot: true,
    plausibility: "easy",
    items: [
      item("Channel Islands Happy shortboard 6ft2", "Channel Islands", 1, 900, "Sports"),
      item("Album Surf longboard 9ft", "Album Surf", 1, 1100, "Sports"),
      item("Christenson fish surfboard 6ft4", "Christenson", 1, 950, "Sports"),
      item("FCS II fins set tri-fin", "FCS", 4, 85, "Sports"),
      item("Creatures of Leisure leash 7ft", "Creatures", 4, 45, "Sports"),
      item("Dakine surf bag single 7ft", "Dakine", 2, 180, "Sports"),
    ],
  }),
  bundle({
    room: "Garage",
    bundle_code: "GAR-GYM-A",
    name: "Home Gym Equipment",
    description: "Professional home gym setup in garage",
    tier: "affordable",
    sweet_spot: false,
    plausibility: "easy",
    items: [
      item("Rogue adjustable dumbbells set 5-50lb", "Rogue", 1, 1200, "Sports"),
      item("Rogue pull-up bar wall mounted", "Rogue", 1, 380, "Sports"),
      item("TRX suspension trainer pro", "TRX", 1, 200, "Sports"),
      item("Peloton bike+ stationary", "Peloton", 1, 2495, "Sports"),
      item("Rubber gym flooring mats 100sqft", "Rubber Flooring Inc", 1, 380, "Sports"),
      item("Olympic barbell with bumper plates 200lb", "Rogue", 1, 850, "Sports"),
    ],
  }),
  bundle({
    room: "Patio",
    bundle_code: "PAT-PLANTS-A",
    name: "Garden & Plants Collection",
    description: "Decorative plants and garden accessories",
    tier: "affordable",
    sweet_spot: true,
    plausibility: "easy",
    items: [
      item("Olive tree large potted", "", 2, 650, "Decorative"),
      item("Fiddle leaf fig tree large potted", "", 2, 280, "Decorative"),
      item("Terracotta planters large set of 4", "", 1, 380, "Decorative"),
      item("Ceramic garden pots assorted 8-piece", "", 1, 120, "Decorative"),
      item("Garden tools set premium", "Sneeboer", 1, 380, "Tools"),
      item("Drip irrigation system", "Rain Bird", 1, 280, "Tools"),
    ],
  }),
  bundle({
    room: "Patio",
    bundle_code: "PAT-ENTERTAIN-A",
    name: "Outdoor Entertaining",
    description: "Outdoor dining and entertaining setup",
    tier: "affordable",
    sweet_spot: false,
    plausibility: "easy",
    items: [
      item("Outdoor bar cart teak", "Gloster", 1, 1200, "Furniture"),
      item("Outdoor wine glasses acrylic set of 8", "Govino", 1, 38, "Kitchen"),
      item("Outdoor dining lanterns", "Crate & Barrel", 6, 85, "Lighting"),
      item("Outdoor throw blankets", "Pendleton", 4, 180, "Textiles"),
      item("Citronella torch set of 4", "Tiki", 1, 45, "Decorative"),
      item("Outdoor speaker weatherproof", "Sonos", 2, 449, "Electronics"),
    ],
  }),
  bundle({
    room: "Bathroom Master",
    bundle_code: "BATH-M-SPA-A",
    name: "Spa Bathroom Essentials",
    description: "Turn the master bath into a spa experience",
    tier: "affordable",
    sweet_spot: true,
    plausibility: "easy",
    items: [
      item("Frette bath towels set of 6", "Frette", 1, 180, "Textiles"),
      item("Frette bath sheets set of 4", "Frette", 1, 220, "Textiles"),
      item("Aesop bathroom product set", "Aesop", 1, 380, "Personal Care"),
      item("La Mer skincare set", "La Mer", 1, 650, "Personal Care"),
      item("Heated towel rack electric", "Warmly Yours", 1, 480, "Appliances"),
      item("Slip silk robe", "Slip", 2, 185, "Clothing"),
      item("Diptyque bathroom candles", "Diptyque", 4, 68, "Consumables"),
    ],
  }),
  bundle({
    room: "Bathroom White",
    bundle_code: "BATH-W-FRESH-A",
    name: "Bathroom Refresh",
    description: "Quality upgrades for the secondary bathroom",
    tier: "affordable",
    sweet_spot: true,
    plausibility: "easy",
    items: [
      item("Brooklinen bath towel set of 6", "Brooklinen", 1, 145, "Textiles"),
      item("Parachute bath mat set of 2", "Parachute", 1, 80, "Textiles"),
      item("Kohler shower head rain style", "Kohler", 1, 380, "Appliances"),
      item("Nécessaire body care set", "Nécessaire", 1, 180, "Personal Care"),
      item("Aesop hand soap set", "Aesop", 3, 85, "Personal Care"),
    ],
  }),
];
