export const ROOM_SUGGESTIONS: Record<string, string[]> = {
  "Living Room": [
    "coffee table books",
    "throw pillows",
    "area rug",
    "floor lamp",
    "table lamp",
    "candles",
    "picture frames",
    "wall art",
    "bookshelf",
    "side table",
    "ottoman",
    "throw blanket",
    "curtains",
    "window shades",
    "decorative vase",
    "plant",
    "fireplace tools",
    "mantle decor",
    "bar cart",
    "wine glasses",
    "cocktail glasses",
    "decanter",
    "record player",
    "vinyl records",
    "speaker",
    "remote controls",
    "board games",
    "puzzles",
    "magazines",
    "sculpture",
    "clock",
    "mirror",
    "humidifier",
    "air purifier",
    "candle holders",
    "diffuser",
    "coasters",
    "serving tray",
    "photo albums",
    "card table",
    "TV stand",
    "cable management",
    "surge protector",
    "extension cord",
    "bluetooth speaker",
    "projector screen",
    "projector",
    "smart home hub",
    "thermostat",
    "smoke detector",
    "carbon monoxide detector",
  ],

  Kitchen: [
    "toaster",
    "microwave",
    "dishwasher",
    "garbage disposal",
    "range hood",
    "coffee maker",
    "espresso machine",
    "kettle",
    "knife block",
    "cutting boards",
    "mixing bowls",
    "measuring cups",
    "measuring spoons",
    "colander",
    "strainer",
    "spatulas",
    "wooden spoons",
    "tongs",
    "ladle",
    "whisk",
    "peeler",
    "can opener",
    "bottle opener",
    "corkscrew",
    "food scale",
    "kitchen timer",
    "oven mitts",
    "pot holders",
    "dish towels",
    "aprons",
    "dish rack",
    "soap dispenser",
    "sponges",
    "trash can",
    "compost bin",
    "paper towel holder",
    "spice rack",
    "spice jars",
    "pantry containers",
    "tupperware",
    "plastic wrap",
    "aluminum foil",
    "parchment paper",
    "ziplock bags",
    "wine rack",
    "fruit bowl",
    "bread box",
    "cookbook stand",
    "cookbooks",
    "placemats",
    "table runner",
    "salt and pepper shakers",
    "napkin holder",
    "dish soap",
    "hand soap",
    "hand cream",
    "first aid kit",
    "fire extinguisher",
    "step stool",
    "island stools",
    "kitchen rug",
    "window herb garden",
  ],

  "Bedroom Orly": [
    "desk lamp",
    "bookshelf",
    "books",
    "alarm clock",
    "mirror",
    "hamper",
    "hangers",
    "shoe rack",
    "storage bins",
    "bedside lamp",
    "phone charger",
    "power strip",
    "extension cord",
    "curtains",
    "blackout shades",
    "fan",
    "humidifier",
    "air purifier",
    "posters",
    "wall art",
    "cork board",
    "white board",
    "desk organizer",
    "pencil cup",
    "notebooks",
    "backpack",
    "duffel bag",
    "luggage",
    "sports equipment",
    "skateboard",
    "surfboard leash",
    "surf wax",
    "guitar stand",
    "guitar picks",
    "guitar strings",
    "guitar tuner",
    "guitar amp",
    "guitar cable",
    "guitar strap",
    "capo",
    "music stand",
    "sheet music",
    "camera bag",
    "memory cards",
    "lens filters",
    "camera cleaning kit",
    "hard drives",
    "USB hubs",
    "monitor stand",
    "keyboard wrist rest",
    "mouse pad",
    "headphone stand",
    "cable organizer",
  ],

  "Bedroom Rafe": [
    "alarm clock",
    "mirror",
    "hamper",
    "hangers",
    "shoe rack",
    "shoe boxes",
    "storage bins",
    "bedside lamp",
    "phone charger",
    "power strip",
    "curtains",
    "blackout shades",
    "fan",
    "humidifier",
    "posters",
    "wall art",
    "safe",
    "watch box",
    "jewelry box",
    "cologne",
    "grooming kit",
    "hair clippers",
    "mirror light",
    "basketball",
    "football",
    "sports cards",
    "display cases",
    "autographed items",
    "team pennants",
    "team jerseys",
    "luggage",
    "duffel bag",
    "gym bag",
    "resistance bands",
    "jump rope",
    "foam roller",
    "yoga mat",
    "gaming chair",
    "gaming headset",
    "gaming mouse",
    "gaming keyboard",
    "controller charger",
    "cable organizer",
    "desk lamp",
    "desk organizer",
  ],

  "David Office / Guest Room": [
    "desk organizer",
    "pen holder",
    "stapler",
    "tape dispenser",
    "scissors",
    "paper clips",
    "sticky notes",
    "notebooks",
    "printer",
    "printer ink",
    "paper shredder",
    "file folders",
    "binders",
    "bookends",
    "books",
    "magazines",
    "desk lamp",
    "monitor stand",
    "keyboard",
    "mouse",
    "mouse pad",
    "headphone stand",
    "webcam",
    "USB hub",
    "cable organizer",
    "power strip",
    "whiteboard",
    "cork board",
    "wall calendar",
    "clock",
    "mirror",
    "guest bedding",
    "guest towels",
    "luggage rack",
    "hangers",
    "alarm clock",
    "bedside lamp",
    "nightstand items",
    "reading glasses",
    "phone charger",
    "curtains",
    "blackout shades",
    "humidifier",
    "fan",
    "air purifier",
    "safe",
    "filing cabinet",
    "document scanner",
    "hard drives",
    "external monitors",
    "podcast microphone",
    "ring light",
    "teleprompter",
    "awards display",
    "screenplay binders",
    "film reference books",
  ],

  Garage: [
    "tool chest",
    "power drill",
    "drill bits",
    "screwdriver set",
    "wrench set",
    "socket set",
    "hammer",
    "level",
    "tape measure",
    "utility knife",
    "pliers",
    "wire cutters",
    "staple gun",
    "heat gun",
    "shop vac",
    "leaf blower",
    "pressure washer",
    "garden hose",
    "hose nozzle",
    "sprinklers",
    "lawn mower",
    "hedge trimmer",
    "weed whacker",
    "pruning shears",
    "shovels",
    "rakes",
    "hoes",
    "wheelbarrow",
    "garden gloves",
    "garden kneeling pad",
    "seed storage",
    "fertilizer",
    "potting soil",
    "flower pots",
    "ladder",
    "step ladder",
    "workbench",
    "pegboard",
    "storage shelving",
    "plastic bins",
    "cargo straps",
    "bungee cords",
    "moving blankets",
    "dolly",
    "hand truck",
    "car jack",
    "jumper cables",
    "tow rope",
    "first aid kit",
    "fire extinguisher",
    "smoke detector",
    "carbon monoxide detector",
    "security camera",
    "garage door opener remote",
    "bike pump",
    "bike repair kit",
    "bike rack",
    "surfboard rack",
    "paddleboard",
    "kayak paddle",
    "life jackets",
    "beach cart",
    "sand toys",
    "camping chairs",
    "camping table",
    "camp stove fuel",
    "waterproof bags",
    "dry bags",
    "snorkel gear",
    "swim fins",
    "goggles",
    "swim caps",
    "pool noodles",
    "footballs",
    "baseballs",
    "baseball bat",
    "tennis ball hopper",
    "tennis ball machine",
    "pickleball paddle",
    "volleyball",
    "soccer ball",
    "golf tees",
    "golf towels",
    "gym bag",
    "yoga mat",
    "foam roller",
    "resistance bands",
    "jump rope",
  ],

  Patio: [
    "outdoor dining table",
    "outdoor dining chairs",
    "outdoor sofa",
    "outdoor coffee table",
    "outdoor side tables",
    "outdoor bar cart",
    "outdoor umbrella",
    "umbrella stand",
    "outdoor rugs",
    "outdoor throw pillows",
    "outdoor throw blankets",
    "outdoor lanterns",
    "string lights",
    "solar lights",
    "tiki torches",
    "fire pit",
    "fire pit cover",
    "outdoor heater",
    "grill",
    "grill cover",
    "grill tools",
    "grill brush",
    "grilling apron",
    "smoker",
    "outdoor pizza oven",
    "outdoor refrigerator",
    "outdoor sink",
    "cooler",
    "ice bucket",
    "outdoor speakers",
    "citronella candles",
    "bug zapper",
    "wind chimes",
    "bird feeder",
    "bird bath",
    "garden statues",
    "planters",
    "potted plants",
    "hanging plants",
    "window boxes",
    "garden art",
    "water feature",
    "outdoor clock",
    "outdoor thermometer",
    "welcome mat",
    "outdoor storage bench",
    "outdoor storage box",
    "pool float",
    "pool noodles",
    "hammock",
    "hammock stand",
    "outdoor chaise lounge",
    "sun umbrella",
    "outdoor mirror",
    "fence art",
    "stepping stones",
    "garden lighting",
  ],

  "Bathroom Master": [
    "towel rack",
    "towel bars",
    "toilet paper holder",
    "toilet brush",
    "trash can",
    "scale",
    "soap dispenser",
    "hand soap",
    "body wash",
    "shampoo",
    "conditioner",
    "hair mask",
    "face wash",
    "toner",
    "moisturizer",
    "eye cream",
    "serum",
    "sunscreen",
    "foundation",
    "makeup brushes",
    "makeup organizer",
    "nail care kit",
    "nail polish",
    "perfume",
    "cologne",
    "deodorant",
    "razor",
    "shaving cream",
    "aftershave",
    "electric toothbrush",
    "water flosser",
    "mouthwash",
    "cotton balls",
    "cotton swabs",
    "tweezers",
    "nail clippers",
    "hair dryer",
    "hair straightener",
    "curling iron",
    "hot rollers",
    "hair brush",
    "comb",
    "hair ties",
    "bobby pins",
    "mirror",
    "magnifying mirror",
    "shower caddy",
    "shower curtain",
    "bath mat",
    "bath rug",
    "bath towels",
    "hand towels",
    "washcloths",
    "bath robe",
    "slippers",
    "candles",
    "diffuser",
    "air freshener",
    "first aid kit",
    "medicine cabinet items",
    "vitamins",
    "prescriptions",
  ],

  "Bathroom White": [
    "towel rack",
    "toilet paper holder",
    "toilet brush",
    "trash can",
    "scale",
    "soap dispenser",
    "hand soap",
    "body wash",
    "shampoo",
    "conditioner",
    "electric toothbrush",
    "toothpaste",
    "mouthwash",
    "dental floss",
    "razor",
    "shaving cream",
    "deodorant",
    "cotton balls",
    "cotton swabs",
    "hair dryer",
    "hair brush",
    "comb",
    "mirror",
    "shower caddy",
    "shower curtain",
    "bath mat",
    "bath towels",
    "hand towels",
    "washcloths",
    "bath robe",
    "candles",
    "air freshener",
    "first aid kit",
    "vitamins",
    "prescriptions",
    "cleaning supplies",
    "plunger",
    "toilet cleaner",
  ],

  "Master Bedroom": [
    "bedside lamp",
    "alarm clock",
    "phone charger",
    "reading glasses",
    "books",
    "notebook",
    "pen",
    "water carafe",
    "sleep mask",
    "earplugs",
    "white noise machine",
    "humidifier",
    "air purifier",
    "fan",
    "electric blanket",
    "heated mattress pad",
    "mattress protector",
    "pillow protectors",
    "extra pillows",
    "extra blankets",
    "curtains",
    "blackout shades",
    "mirror",
    "full length mirror",
    "jewelry box",
    "watch box",
    "watch winder",
    "cufflinks box",
    "tie rack",
    "belt rack",
    "shoe trees",
    "shoe bags",
    "clothes brush",
    "lint roller",
    "fabric shaver",
    "steamer",
    "iron",
    "ironing board",
    "hamper",
    "laundry bag",
    "safe",
    "picture frames",
    "wall art",
    "decorative objects",
    "candles",
    "diffuser",
    "flowers",
    "plants",
    "clock",
    "television",
    "Apple TV",
    "soundbar",
    "cable box",
    "DVD player",
    "books on nightstand",
    "magazines",
  ],

  "Master Bathroom": [
    "heated towel rack",
    "towel warmer",
    "bath tray",
    "bath pillow",
    "bath salts",
    "bath bombs",
    "loofa",
    "body brush",
    "foot scrub",
    "facial steamer",
    "jade roller",
    "gua sha",
    "LED face mask",
    "microneedling roller",
    "teeth whitening kit",
    "tongue scraper",
    "sauna blanket",
    "massage tool",
    "hair oil",
    "beard trimmer",
    "beard oil",
    "nail drill",
    "UV nail lamp",
    "gel nail kit",
    "pedicure kit",
    "foot bath",
    "towels",
    "bath sheets",
    "guest hand towels",
    "washcloths",
    "robes",
    "slippers",
    "scale",
    "blood pressure monitor",
    "thermometer",
    "medicine cabinet",
    "first aid kit",
    "vitamins",
    "prescriptions",
    "candles",
    "diffuser",
    "plants",
    "artwork",
    "decorative items",
    "soap dish",
    "toothbrush holder",
    "cotton jar",
    "q-tip holder",
    "lotion dispenser",
    "perfume tray",
    "makeup mirror",
    "lighted mirror",
  ],

  "Master Closet": [
    "jewelry organizer",
    "jewelry box",
    "watch box",
    "watch winder",
    "ring dish",
    "bracelet stand",
    "necklace organizer",
    "earring organizer",
    "sunglasses organizer",
    "hat boxes",
    "hat rack",
    "shoe boxes",
    "shoe bags",
    "shoe trees",
    "boot shapers",
    "handbag hooks",
    "handbag organizer",
    "purse shelf",
    "scarf rack",
    "belt rack",
    "tie rack",
    "cufflinks box",
    "tie clips",
    "collar stays",
    "suit bags",
    "garment bags",
    "cedar blocks",
    "cedar hangers",
    "velvet hangers",
    "specialty hangers",
    "drawer dividers",
    "drawer organizers",
    "folding board",
    "lint roller",
    "clothes brush",
    "fabric shaver",
    "steamer",
    "iron",
    "mirror",
    "full length mirror",
    "lighting",
    "safe",
    "security box",
    "luggage",
    "travel organizers",
    "packing cubes",
    "laundry bag",
    "hamper",
    "hooks",
    "valet stand",
    "clothes rack",
    "folding chair",
    "step stool",
    "storage boxes",
    "storage baskets",
  ],
};

export function suggestionAlreadyPresent(suggestion: string, existingItems: { description: string }[]): boolean {
  const s = suggestion.toLowerCase();
  const words = s.split(" ").filter((w) => w.length > 3);
  return existingItems.some((item) => {
    const d = item.description.toLowerCase();
    return words.some((w) => d.includes(w));
  });
}

export function getNextSuggestions(room: string, existingItems: { description: string }[], offset: number): string[] {
  const all = ROOM_SUGGESTIONS[room] || [];
  const available = all.filter((s) => !suggestionAlreadyPresent(s, existingItems));
  return available.slice(offset, offset + 5);
}
